---
- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: present

- name: Clone neovim config
  ansible.builtin.git:
    clone: yes
    dest: "{{ ansible_user_dir }}/.config/nvim"
    repo: git@github.com:spiider/nvim.git
    single_branch: yes
    update: yes
    version: main
